### ISSUE TITLE
Upgrading from 0.7.2 to 0.8.0 breaks existing applications

### ISSUE THREAD

**Issue by OdyX** [evonove/django-oauth-toolkit#236]
Trying to upgrade django-oauth-toolkit from 0.7.2 to 0.8.0 breaks, apparently because of missing migrations:
```
ProgrammingError: column oauth2_provider_application.skip_authorization does not exist
LINE 1: ...nt_secret", "oauth2_provider_application"."name", "oauth2_pr...
                                                             ^
```
This, when trying to edit an existing application through the administration, or otherwise trying to use it.

**Comment by synasius** [comment]
Hi @OdyX 
migrations have been fixed in master. I just released a 0.8.1 on pypi that includes migrations for both south and django>1.7

**Comment by OdyX** [comment]
Sorry, but 0.8.1 didn't solve it. It's now broken differently.

If you have an application already setup in 0.7.2, the `./manage.py migrate` run after installing django-oauth-toolkit 0.8.1 will get you this error:
```
  Applying oauth2_provider.0001_initial...Traceback (most recent call last):
  File "./manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "…/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "…/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "…/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "…/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "…/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "…/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "…/lib/python2.7/site-packages/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "…/lib/python2.7/site-packages/django/db/migrations/migration.py", line 108, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "…/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 36, in database_forwards
    schema_editor.create_model(model)
  File "…/lib/python2.7/site-packages/django/db/backends/schema.py", line 262, in create_model
    self.execute(sql, params)
  File "…/lib/python2.7/site-packages/django/db/backends/schema.py", line 103, in execute
    cursor.execute(sql, params)
  File "…/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "…/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "…/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "…/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "oauth2_provider_application" already exists
```

**Comment by synasius** [comment]
Hi,

have you upgraded to django>1.7? It looks like you're not using south
anymore.

You should first run all the south migrations, then you switch to django1.8
and fake the initial migration



2015-04-28 10:16 GMT+02:00 Didier Raboud <notifications@github.com>:

> Sorry, but 0.8.1 didn't solve it. It's now broken differently.
>
> If you have an application already setup in 0.7.2, the ./manage.py migrate
> run after installing django-oauth-toolkit 0.8.1 will get you this error:
>
>   Applying oauth2_provider.0001_initial...Traceback (most recent call last):
>   File "./manage.py", line 17, in <module>
>     execute_from_command_line(sys.argv)
>   File "…/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
>     utility.execute()
>   File "…/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "…/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
>     self.execute(*args, **options.__dict__)
>   File "…/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
>     output = self.handle(*args, **options)
>   File "…/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
>     executor.migrate(targets, plan, fake=options.get("fake", False))
>   File "…/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
>     self.apply_migration(migration, fake=fake)
>   File "…/lib/python2.7/site-packages/django/db/migrations/executor.py", line 102, in apply_migration
>     migration.apply(project_state, schema_editor)
>   File "…/lib/python2.7/site-packages/django/db/migrations/migration.py", line 108, in apply
>     operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
>   File "…/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 36, in database_forwards
>     schema_editor.create_model(model)
>   File "…/lib/python2.7/site-packages/django/db/backends/schema.py", line 262, in create_model
>     self.execute(sql, params)
>   File "…/lib/python2.7/site-packages/django/db/backends/schema.py", line 103, in execute
>     cursor.execute(sql, params)
>   File "…/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
>     return super(CursorDebugWrapper, self).execute(sql, params)
>   File "…/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
>     return self.cursor.execute(sql, params)
>   File "…/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "…/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
>     return self.cursor.execute(sql, params)
> django.db.utils.ProgrammingError: relation "oauth2_provider_application" already exists
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evonove/django-oauth-toolkit/issues/236#issuecomment-96969277>
> .
>



-- 
Federico Frenguelli

**Comment by OdyX** [comment]
No. We're using Django==1.7.7, that doesn't use South migrations.

There should be no need to fake migrations (on all the instances we have for this project…) to upgrade libraries!

**Comment by synasius** [comment]
2015-04-28 13:20 GMT+02:00 Didier Raboud <notifications@github.com>:

> No. We're using Django==1.7.7, that doesn't use South migrations.
>

Ok, what I said before still applies. Migrate your databases using South
and then fake the initial migration.
Otherwise you can provide your own custom migrations for DOT as documented
here
https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-MIGRATION_MODULES
Or you can add the column manually with a script and then fake the initial
migration.

These are three possible solutions to your problem. If you thinks there's a
better approach that we can integrate into DOT just send us a PR.
Contributions are welcome, as always!


> There should be no need to fake migrations (on all the instances we have
> for this project…) to upgrade libraries!
>
Of course I agree. Consider that moving from south to native migrations and
supporting both wasn't an easy task, so there a lot of corner cases which
are not supported
out-of-the-box but one can easily find workarounds.

Thanks

-- 
Federico Frenguelli

**Comment by xleon** [comment]
I´ve never used south in my project and I get the very same error:
"django.db.utils.ProgrammingError: relation "oauth2_provider_application" already exists"

A dirty workaround is to edit this file [virtualenv]/lib/python2.7/site-packages/oauth2_provider/migrations/0002_08_updates.py and comment the first operation:

# migrations.AddField(
        #      model_name='Application',
        #      name='skip_authorization',
        #      field=models.BooleanField(default=False),
        #      preserve_default=True,
        # ),

I don´t understand why this migration is adding the "skip_authorization" field if it was already created in the previous version

**Comment by JensTimmerman** [comment]
can this be documented a bit?
I'm still having issues.
I'm on django1.8, I updated from oauth-toolkit 0.7.1 to 0.10.0
and I'm seeing this error, also with --fake-initial

```
[root@tropius2 ~]# django-admin migrate --fake-initial oauth2_provider
/usr/lib/python2.7/site-packages/rest_framework/settings.py:23: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils import importlib

/usr/lib/python2.7/site-packages/rest_framework/serializers.py:128: RemovedInDjango19Warning: SortedDict is deprecated and will be removed in Django 1.9.
  return SortedDict(fields)

Operations to perform:
  Apply all migrations: oauth2_provider
Running migrations:
  Rendering model states... DONE
  Applying oauth2_provider.0001_initial...Traceback (most recent call last):
  File "/bin/django-admin", line 5, in <module>
    management.execute_from_command_line()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/usr/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/usr/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "oauth2_provider_application" already exists

```

**Comment by JensTimmerman** [comment]
seems to have worked with `django-admin migrate oauth2_provider 0001 --fake`

**Comment by james-aiwip** [comment]
@JensTimmerman unfortunatley these don't work for me :(

**Comment by james-aiwip** [comment]
That didn't solve it for me, I had to manually run `makemigrations oauth2_provider` in order for django to figure out what it should or should not be doing.
